spring.application.name=CW_TgBot
spring.datasource.url=jdbc:postgresql://localhost:5432/telegramBot
spring.datasource.username=myUser
spring.datasource.password=myPasswordForMyUser
telegram.bot.token=7587435872:AAEq-fVpQ42pHiMjWWRg7SZHg7hZ8QIyzhw
telegram.bot.username=SpringBootDemo76Bot
spring.jpa.hibernate.ddl-auto=update


spring.liquibase.change-log=classpath:liquibase/changelog-master.yml